CREATE TABLE IF NOT EXISTS FEEDBACK(
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    TELEPHONE_NUMBER TEXT NOT NULL,
    EMAIL_ADDRESS TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    SUBJECT TEXT NOT NULL,
    MESSAGE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    USER_NAME TEXT NOT NULL,
    TELEPHONE_NUMBER TEXT NOT NULL,
    EMAIL_ADDRESS TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    JC INT NOT NULL,
    SUBSCRIPTIONS TEXT NOT NULL,
    PROJECTS TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJECT(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME_PROJECT TEXT NOT NULL,
    CATEGORY_PROJECT TEXT NOT NULL,
    DESCRIPTION PROJECT TEXT NOT NULL,
    NAME_FILE_PROJECT TEXT NOT NULL,
    IMAGE_PROJECT BLOB DEFAULT NULL,
    AUTHOR_USER_ID INTEGER NOT NULL,
    AUTHOR_FIRST_NAME TEXT NOT NULL,
    AUTHOR_LAST_NAME TEXT NOT NULL,
    AUTHOR_USER_NAME TEXT NOT NULL,
    DATE_OF_CREATION TEXT NOT NULL
);

